# Site settings
title: Polydelphia Election
email: polydelphia@gmail.com
description: >
  Polydelphia is electing a new Steering Committee! All the
  candidates are displayed below. Happy Voting!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://polydelphia.org" # the base hostname & protocol for your site, e.g. http://example.com

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: default    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  candidates:
    output: true
    permalink: /candidates/:name:output_ext
  test_candidates:
    output: true
    permalink: /test/candidates/:name:output_ext
